ALTER TABLE attendance
ADD COLUMN IF NOT EXISTS reason VARCHAR(50),
ADD COLUMN IF NOT EXISTS marked_by UUID REFERENCES users(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS marked_at TIMESTAMP NOT NULL DEFAULT now();
